{
	"data": "ENC[AES256_GCM,data:x9LVToubnSuXUBn50dU+K2IqbdHCTkB6LGH/5ILNbc+sl3ta/7QUj5jQ1i7IGwofAvodefgvzhzGp3RfWCtKI0Zls+MHkyBL1DgGuYn1bpWYk9xtz+EIr5QwSvB87ZzJLU3T8iG3BDWuE/McRUgXob83EgWNZ7aP4peersIXZRGbWj+7SMkEm+40nAtWGtbLZf0EXnx9h7qv/nnEYj4y4k7ZY6hQ3OOuvX5LqLeUWWaKaxjk7rjbO0/JeMyswz7x/9vPbBSfj5Mlsq48JdsJ5xytH/nS9YTWEiyxYOlFkEPty8rm5muWqCe0mW0AAp4GodppJl+Gq3vhCTOGpV9MMT6JZj3JTn++Js38v4NMJsI5KQwAYNHlduOWHVguPGpdBSGcSMaa8DzcJ1RDBb9cEohCqQ7eMdn6gVO68Ezdj7Ay7Grey+BSeZ3XkeYdiaACUXVKsLP+UKO5gtYahN4hwHrpjrXPdZMZlc01xMpOtZMQk1tNRgEDsK/0io1a8EVuR1VuP9F7tFllYjzuzxzovmMPriK+iUG97fWdlXqRNs3KPCFmauvxIK5nS9MUmMfxHK0MQk37/o/1HNeu3FetVNwSmaprJNybRgXyVTH2hw1hdyM7cmpFU42sLPzd6/j27alxEDaEt4uQxp2aJsymrd/4B6HhHHoe7ocOxAXRp04=,iv:s5mtPlBHvmhNZEyU2hVF/ocI0FjUjiuXgt4m5HFj3es=,tag:deKFJOO01eascSSv5y8P0Q==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINbw4Tc1nPQuOyzaoPDViG0WNp9QKJB+C6Rme439RMbC root@mg-VirtualBox",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFRpb213USBjYlNu\nNEZaY0YzT3NsUm5YaTNsZE1WZ2xvamNYUmlUbUE3ckF0Sk1mM0FNCjljTXZWN0dn\nY3R1QWN1SUZ6TG16MzZYL3ZjcStaYmZCVFFxT1FjUUdSMzAKLS0tIFJHU3hISHhq\nU1NjaG5zWXh3VUlTSzBZTlVjbUVBU0VSSkxENEJGWStiL1kKUjXjatFOKZYAdi5s\nTbNq4lmVq6PCuPxfz3VzGTIxs+sqaOwtl9QhMIXj1WieC8Na73BJ6DmtJXvsO9AG\n89WMOA==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-02-15T19:47:20Z",
		"mac": "ENC[AES256_GCM,data:xkkt/TPmAZXv1FOmazSu2LoNFAEmmNMW7QtYcno5R46yo2K65dSTlS/F1B/rkGfbrAQ89PgOL4EzRWC9duIbGu3OODnmK8nAasvbbRNMvL+O/UI9gwuHsquvB8VJTraCWbuQ64CBVCsafu4Wy2t25K222HZ6W2XT19XneHUDaTY=,iv:3GpQ11+Zgoo+3bO6LRzfmZZzGFBT2Rq5ubaqVBNvxB4=,tag:VA4A6Fze4xvtIcx6Bp2HeQ==,type:str]",
		"version": "3.11.0"
	}
}
