[global]
keyboard = "en-us"
country = "us"
fqdn = "pveauto.testinstall"
mailto = "mail@no.invalid"
timezone = "America/Chicago"
root_password = "1234"
root_ssh_keys = []

[network]
source = "from-dhcp"

[disk-setup]
filesystem = "ext4"
disk-list = "/dev/sda"