[global]
keyboard = "en-us"
country = "us"
fqdn = "pveauto.testinstall"
mailto = "mail@no.invalid"
timezone = "America/Chicago"
root-password = "12345678"

[network]
source = "from-dhcp"

[disk-setup]
filesystem = "ext4"
disk-list = ["/dev/sda"]