[global]
keyboard = "en-us"
country = "ru"
fqdn = "pve.karazhan.local"
mailto = "heimcbk201@gmail.com"
timezone = "Russia/Moscow"
root-password = "12345678"

[network]
source = "from-dhcp"

[disk-setup]
filesystem = "ext4"
disk-list = ["/dev/sda"]
