{
	"data": "ENC[AES256_GCM,data:Q8xZso2QFrAUQtfVrnvvNf1D7s1saZqvIPeX0D7c2KeWPfCZfyhH4WQc9JnvUDHVwxYUW4rc3t6szqADbdZF40z+jCAr9PB3JZZhBiu0Tw4fE3Kt9lz5ewKRpYF7TpAaZ+1O/y5MYHjlh4alw1vd1ni5DDuP7QLe/p4bljxFkbfjM8zymk4awMh7cDOBH5BSyzSSt3zit7okROBi3e1i5IrE9Ya4RohbAolHiyqTssLej+JIsMSgxLjET3IkLWigUaOcFDqpcw2j+lUileWQF52470nU2VshArI/2QSxvO5lPl2dtJ502LIhh/JIzqcpI3oGejUSeBBPqutV6srmOYJtUw1MxGg/5rhQBqsANI8cBf9t5tiYLgkRZUXS+ULS4bqzZh4PBCgFpoUjz+B/Hyx5W7nWHTKf214g4kr51DmkJRn+mQXwJhT9ptEcfPKRlLiND9d25DFOnw3y2oEEgJtarKhOS/lHLNVrxZJpLMIXAKBvF4ecgeIDVtYWRD4TEpYaUlxS4/kDzCJt4Lwq9Tc3qRd0/LU0IeGLjDNh3lKm0c2L1dXLqCkakYxIqO27DZk23QL1OlO+WuLr2EHCOvtO0g4taKQj21+EBwVHRnzPlUPbbg9Nci/N74GLfxJHFmFI/f9fLB8r3tyJsWnIsLFLljJ7oEs=,iv:riC9dvDT75QQncKVsxtDaz0LpuRiTAWRUQK8xTuFXVU=,tag:K44LBDwjZ+RozjPq6H0sMQ==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINbw4Tc1nPQuOyzaoPDViG0WNp9QKJB+C6Rme439RMbC root@mg-VirtualBox",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFRpb213USBBUk8w\nRER4dUZ2cjNYVWZ1VmN6WFZjTXlkdm1aMDAwbDNDbVBPYmh6Y2pjCktnUk5JMlNy\nRVBwbFY0NXRpTXNMUkYvamNEdk10Rk9kZ3FVQUhHQXFXTFkKLS0tIHdIK0FFU24z\nQXdJNGR1WGowUDhwbllNbnc5VVcwVXdYQll2dUp0L2IzZG8Ka4PH9areg42WTsYg\nFrR1XqnVO75ioRTmM5gAeNoUKzzXvD3daWQ+ErBRjKubGlScarGMkMXwu0FcI41u\nd7hEig==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-02-15T19:41:47Z",
		"mac": "ENC[AES256_GCM,data:wKKYznAX2dNdjPDvCLgHbvsQMpLWNM74Xe2pXKw9iNsSwZ49/LKFgv1XYpk56JLy+pjFokmDIm7N6lRDRfd5rctMc6D1qa/nnJh2if5/juW8UZHeL0DqjVfmXRFVfRHP+14TlVZOiq/Ofyq0vRvBi9bnqf6lQCGzNCmZDtg3oPQ=,iv:yLUelHVAWw5YA3CZnJSZk0Ohxm6Ty7qp2z+tSYnA8Fo=,tag:z5dNlE+oV39qJxmaOOGBjA==,type:str]",
		"version": "3.11.0"
	}
}
